# Generated by Django 5.2.7 on 2025-10-04 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_options_customuser_is_verified_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FirebaseToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.TextField(unique=True)),
                (
                    "device_info",
                    models.CharField(
                        blank=True, help_text="Device/browser info", max_length=200
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="firebase_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Firebase Token",
                "verbose_name_plural": "Firebase Tokens",
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="users_fireb_user_id_5c33b3_idx",
                    ),
                    models.Index(fields=["token"], name="users_fireb_token_120fe4_idx"),
                ],
            },
        ),
    ]
