# Generated by Django 5.2.7 on 2025-10-03 12:54

import django.core.validators
import django.db.models.deletion
import hub.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['due_date', '-created_at'], 'verbose_name': 'Assignment', 'verbose_name_plural': 'Assignments'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['-created_at'], 'verbose_name': 'Material', 'verbose_name_plural': 'Materials'},
        ),
        migrations.AlterModelOptions(
            name='studentprogress',
            options={'verbose_name': 'Student Progress', 'verbose_name_plural': 'Student Progress'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name'], 'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
        migrations.AddField(
            model_name='assignment',
            name='instructions',
            field=models.TextField(blank=True, help_text='Detailed instructions for students'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='max_score',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AddField(
            model_name='assignment',
            name='priority',
            field=models.CharField(choices=[('low', 'Low Priority'), ('medium', 'Medium Priority'), ('high', 'High Priority'), ('urgent', 'Urgent')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='assignment',
            name='submission_format',
            field=models.CharField(blank=True, help_text='Expected submission format (e.g., PDF, handwritten, online quiz)', max_length=200),
        ),
        migrations.AddField(
            model_name='assignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='material',
            name='download_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags (e.g., algebra, fractions, beginner)', max_length=500),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='hub.assignment'),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='graded_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('needs_review', 'Needs Review')], default='not_started', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='submission_file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/', validators=[hub.models.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='submission_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='teacher_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='time_spent_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Total time spent in minutes'),
        ),
        migrations.AddField(
            model_name='subject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assigned_to',
            field=models.ManyToManyField(limit_choices_to={'user_type': 'student'}, related_name='assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='hub.material'),
        ),
        migrations.AlterField(
            model_name='material',
            name='estimated_time',
            field=models.IntegerField(help_text='Estimated time in minutes (1-1440)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)]),
        ),
        migrations.AlterField(
            model_name='material',
            name='external_link',
            field=models.URLField(blank=True, help_text='External resource link'),
        ),
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(blank=True, help_text='Upload educational material (max 50MB)', null=True, upload_to=hub.models.material_upload_path, validators=[hub.models.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'ppt', 'pptx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png', 'gif', 'svg', 'mp4', 'avi', 'mov', 'wmv', 'mp3', 'wav', 'ogg', 'zip', 'rar', 'txt'])]),
        ),
        migrations.AlterField(
            model_name='material',
            name='grade_level',
            field=models.CharField(choices=[('k', 'Kindergarten'), ('1', 'Grade 1'), ('2', 'Grade 2'), ('3', 'Grade 3'), ('4', 'Grade 4'), ('5', 'Grade 5'), ('6', 'Grade 6'), ('7', 'Grade 7'), ('8', 'Grade 8'), ('9', 'Grade 9'), ('10', 'Grade 10'), ('11', 'Grade 11'), ('12', 'Grade 12'), ('university', 'University Level')], max_length=20),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=models.CharField(choices=[('worksheet', 'Worksheet'), ('test', 'Test'), ('assignment', 'Assignment'), ('reading', 'Reading Material'), ('video', 'Video'), ('audio', 'Audio'), ('presentation', 'Presentation'), ('game', 'Educational Game'), ('reference', 'Reference Material')], max_length=20),
        ),
        migrations.AlterField(
            model_name='material',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='hub.subject'),
        ),
        migrations.AlterField(
            model_name='material',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_materials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='hub.material'),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='score',
            field=models.PositiveIntegerField(blank=True, help_text='Score as percentage (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='student',
            field=models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subject',
            name='color_code',
            field=models.CharField(default='#007bff', help_text='Hex color code (e.g., #FF5733)', max_length=7),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['due_date', 'is_active'], name='hub_assignm_due_dat_f008d0_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['created_by', 'created_at'], name='hub_assignm_created_e90e40_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['subject', 'grade_level'], name='hub_materia_subject_0e9b1d_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['material_type', 'difficulty_level'], name='hub_materia_materia_673dd6_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['is_active', 'created_at'], name='hub_materia_is_acti_3260e8_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprogress',
            index=models.Index(fields=['student', 'status'], name='hub_student_student_209548_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprogress',
            index=models.Index(fields=['material', 'completed_at'], name='hub_student_materia_db6d70_idx'),
        ),
    ]
