# Generated by Django 5.2.7 on 2025-10-03 14:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import hub.models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0002_alter_assignment_options_alter_material_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignmentSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "submission_file",
                    models.FileField(
                        blank=True,
                        help_text="Upload your completed assignment (max 50MB)",
                        null=True,
                        upload_to="submissions/%Y/%m/",
                        validators=[
                            hub.models.validate_file_size,
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "txt",
                                ]
                            ),
                        ],
                    ),
                ),
                (
                    "submission_text",
                    models.TextField(
                        blank=True,
                        help_text="Type your answer here if no file upload needed",
                    ),
                ),
                (
                    "submission_notes",
                    models.TextField(
                        blank=True,
                        help_text="Any additional notes or questions for your teacher",
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("graded", "Graded"),
                            ("returned", "Returned for Revision"),
                        ],
                        default="submitted",
                        max_length=20,
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+ (97-100%)"),
                            ("A", "A (93-96%)"),
                            ("A-", "A- (90-92%)"),
                            ("B+", "B+ (87-89%)"),
                            ("B", "B (83-86%)"),
                            ("B-", "B- (80-82%)"),
                            ("C+", "C+ (77-79%)"),
                            ("C", "C (73-76%)"),
                            ("C-", "C- (70-72%)"),
                            ("D", "D (60-69%)"),
                            ("F", "F (Below 60%)"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "numeric_score",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Score out of 100",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "teacher_feedback",
                    models.TextField(
                        blank=True, help_text="Feedback and comments from teacher"
                    ),
                ),
                ("graded_at", models.DateTimeField(blank=True, null=True)),
                ("revision_requested", models.BooleanField(default=False)),
                (
                    "revision_notes",
                    models.TextField(blank=True, help_text="What needs to be improved"),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="hub.assignment",
                    ),
                ),
                (
                    "graded_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"user_type": "teacher"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="graded_assignment_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignment_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Assignment Submission",
                "verbose_name_plural": "Assignment Submissions",
                "ordering": ["-submitted_at"],
                "indexes": [
                    models.Index(
                        fields=["student", "submitted_at"],
                        name="hub_assignm_student_ed9796_idx",
                    ),
                    models.Index(
                        fields=["assignment", "status"],
                        name="hub_assignm_assignm_0918fe_idx",
                    ),
                    models.Index(
                        fields=["graded_by", "graded_at"],
                        name="hub_assignm_graded__01d58d_idx",
                    ),
                ],
                "unique_together": {("assignment", "student")},
            },
        ),
    ]
