name: Django CI

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: pg_tutoring_ci
          POSTGRES_USER: django
          POSTGRES_PASSWORD: django
        ports: ["5432:5432"]
        options: >-
          --health-cmd "pg_isready -U postgres" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Create .env for CI
        run: |
          cat > .env << 'EOF'
          SECRET_KEY=ci-secret-key
          DEBUG=False
          ALLOWED_HOSTS=localhost
          DB_NAME=pg_tutoring_ci
          DB_USER=django
          DB_PASSWORD=django
          DB_HOST=127.0.0.1
          DB_PORT=5432
          REDIS_HOST=127.0.0.1
          REDIS_PORT=6379
          SECURE_SSL_REDIRECT=False
          SESSION_COOKIE_SECURE=False
          CSRF_COOKIE_SECURE=False
          EOF
      - name: Run Django checks
        run: |
          python manage.py check
      - name: Make migrations check
        run: |
          python manage.py makemigrations --check --dry-run
      - name: Run tests
        run: |
          pip install coverage
          coverage run manage.py test -v 2
          coverage report --fail-under=60